/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.3-8-g292b30bbe0-20251203"
#endif /* AVUTIL_FFVERSION_H */
